### PR TITLE
Feat/home page

### PR DESCRIPTION
**Pull request by talentlessDeveloper**
### Description
Created the homepage including page layouts for header and footer.
Not 100% done, still needs a lot of adjustments.

### CODE REVIEW

**Comment by talentlessDeveloper** [comment]
@midevictor  you can review this before we merge.

**Review by midevictor — APPROVED** [review]
Great Work Done!

**Review by talentlessDeveloper — COMMENTED** [review]
Thanks!

**Review by midevictor — APPROVED** [review]
Nice Work!

**Review by midevictor — APPROVED** [review]

**Review by midevictor — APPROVED** [review]

**Pull request merged**
